# Generated by Django 4.2.7 on 2023-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('feed_back', models.CharField(max_length=1000)),
                ('picture', models.FileField(upload_to='feedback_pics/')),
            ],
        ),
    ]
