# Generated by Django 4.2.7 on 2023-12-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
