# Generated by Django 4.2.7 on 2023-11-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feed_back',
            field=models.FileField(upload_to='feedbacks/'),
        ),
    ]
