# Generated by Django 4.2.7 on 2023-11-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0002_alter_feedbacks_feed_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feed_back',
            field=models.CharField(max_length=1000),
        ),
    ]
