# Generated by Django 4.2.7 on 2023-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0006_remove_attendance_date_attendance_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='montly_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0)),
                ('breakfast', models.IntegerField(default=0)),
                ('lunch', models.IntegerField(default=0)),
                ('dinner', models.IntegerField(default=0)),
            ],
        ),
    ]
