# Generated by Django 4.2.7 on 2023-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0010_rating_model_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('student_bhawan', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
