# Generated by Django 4.2.7 on 2023-12-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0011_student_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_total',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studeck.student_info'),
        ),
    ]
