# Generated by Django 4.2.7 on 2023-12-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0012_alter_user_total_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_total',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studeck.student_info'),
        ),
    ]
