# Generated by Django 4.2.7 on 2023-12-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0013_alter_user_total_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkpresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.IntegerField(default=0)),
                ('lunch', models.IntegerField(default=0)),
                ('dinner', models.IntegerField(default=0)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studeck.student_info')),
            ],
        ),
    ]
