# Generated by Django 4.2.7 on 2023-12-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0015_alter_checkpresence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpresence',
            name='date',
        ),
    ]
