# Generated by Django 4.2.7 on 2023-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0018_checkpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
