# Generated by Django 4.2.7 on 2023-12-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0019_food_items_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
