# Generated by Django 4.2.7 on 2023-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0021_alter_rating_model_food_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_model',
            name='food_item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rating_model',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
