# Generated by Django 4.2.7 on 2023-12-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0022_alter_rating_model_food_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_model',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studeck.food_items'),
        ),
        migrations.AlterField(
            model_name='rating_model',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studeck.student_info'),
        ),
    ]
