# Generated by Django 4.2.7 on 2023-12-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0023_alter_rating_model_food_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studeck.student_info'),
        ),
    ]
