# Generated by Django 4.2.7 on 2023-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studeck', '0024_alter_feedbacks_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
