# Generated by Django 4.2.7 on 2023-11-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdeck', '0002_remove_staff_info_staff_name_staff_info_staff_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_info',
            name='staff_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
