# Generated by Django 4.2.7 on 2023-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdeck', '0003_alter_staff_info_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_info',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
