# Generated by Django 4.2.7 on 2023-11-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdeck', '0004_staff_info_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
