# Generated by Django 4.2.7 on 2023-11-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffdeck', '0005_messfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messfile',
        ),
    ]
