# Generated by Django 4.2.7 on 2023-11-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdeck', '0006_delete_messfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/')),
            ],
        ),
    ]
