# Generated by Django 4.2.7 on 2023-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdeck', '0007_messupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messupload',
            name='file',
            field=models.FileField(upload_to='file_uploads/'),
        ),
    ]
